services:
    extensions_product_options_connector.provider.form.job_instance:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                csv_product_options_import: pim-job-instance-product-options-import
        tags:
            - { name: pim_enrich.provider.form }
