parameters:
    extensions_product_options_connector.reader.file.csv_product.class: Extensions\Bundle\ProductOptionsConnectorBundle\Reader\ProductReader

services:
    extensions_product_options_connector.reader.file.csv_product:
        class: '%extensions_product_options_connector.reader.file.csv_product.class%'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@extensions_product_options_connector.array_converter.flat.product'
            - '@pim_connector.reader.file.media_path_transformer'
            - []